# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9457048458aac2049fefeb4af77b7ce11882cc487af9e173d5799a601903afb6e31bae3b686931ecf404b0f0ca229bff5797ad294554ec7b11cc6c79a41f95c

test:
  secret_key_base: 3a4fe8b75ed2104d455abb5d176e85b87509a8f0da940dcf737b02f5f04b6fd43524377796bc2593f7753163c22e4778e6b01c209edf905080e9d1a6e1016629

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
